fun main(){
    println("         ,")
    println("        /|      __")
    println("       / |   ,-~ /")
    println("      Y :|  //  /")
    println("      | jj /( .^")
    println("      >-\"~\"-v\"")
    println("     /       Y")
    println("    jo  o    |")
    println("   ( ~T~     j")
    println("    >._-' _./")
    println("   /   \"~\"  |")
    println("  Y     _,  |")
    println(" /| ;-\"~ _  l")
    println("/ l/ ,-\"~    \\")
    println("\\//\\/      .- \\")
    println(" Y        /    Y")
    println(" l       I     !")
    println(" ]\\      _\\    /\"\\")
    println("(\" ~----( ~   Y.  )")
    println("Bunny")
}